[package]
name = "quick_cache"
version = "0.2.2"
edition = "2021"
description = "Lightweight and high performance concurrent cache"
repository = "https://github.com/arthurprs/quick-cache"
authors = ["Arthur Silva <arthurprs@gmail.com>"]
license = "MIT"
keywords = ["lru", "concurrent", "cache"]
categories = ["caching", "concurrency", "data-structures"]
readme = "README.md"
exclude = ["fuzz"]

[features]
default = ["dep:ahash"]

[dependencies]
ahash = { optional = true, version = "0.8" }
hashbrown = { version = "0.13", default-features = false, features = ["raw", "inline-more"] }
parking_lot = "0.12"

[dev-dependencies]
criterion = "0.3"
rand = { version = "0.8", features = ["small_rng"] }
rand_distr = "0.4"

[[bench]]
name = "benchmarks"
harness = false
